server:
  port: 8000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      mvc:
        routesMap:
          films-microservice:
            uri: lb://films-microservice
            predicates:
              - Path=/api/film/**
          books-microservice:
            uri: lb://books-microservice
            predicates:
              - Path=/api/book/**
          users-microservice:
            uri: lb://users-microservice
            predicates:
              - Path=/api/user/**
            filters:
              - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8500/realms/realm-JWT/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8500/realms/realm-JWT/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:8500/realms/realm-JWT/protocol/openid-connect/token
          registration:
            jwt-client:
              provider: keycloak
              client-id: jwt-client
              client-secret: BYqALwtbNvL3ODc1BRJdvWrWcwWQFnzn
              authorization-grant-type: authorization_code
              redirect-uri: "${baseUrl}/login/oauth2/code/jwt-client"