server:
  port: 8001
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/jwt-tutorial
      database: jwt-tutorial
      auto-create-collection: true
      auto-index-creation: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost