server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          #default-label: master
          default-label: keycloak
          uri: https://github.com/repicam/microservicios-JWTgateway
          search-paths: configurations
  application:
    name: config-server